name: NASA project CI
# Triggers when a new branch is pushed or a pull request is opened
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
  build:
    env:
      CI: true # This is a CI build, removes watch
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest # or any other supported OS
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run install-client