name: NASA project CI
# Triggers when a new branch is pushed or a pull request is opened
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
  build:
    env:
      CI: true # This is a CI build, removes watch for client test (press q to exit)
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      # Runs the build script on multiple node versions
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest # or any other supported OS
    steps:
      # Uses pre-defined actions from the GitHub Actions marketplace
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Mock the database with "MongoDB in GitHub Actions"
      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      # Runs steps in the same order as defined
      - run: npm install
      - run: npm run install-client
      - run: npm run test