name: NASA project CI
# Triggers when a new branch is pushed or a pull request is opened
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest # or any other supported OS
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
